name: lmslocal_flutter
description: "LMSLocal mobile app for Last Man Standing competitions"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP client
  dio: ^5.4.0
  
  # State management
  flutter_riverpod: ^2.4.0
  
  # Local storage
  shared_preferences: ^2.2.0
  
  # JSON serialization
  json_annotation: ^4.9.0
  
  # Material 3 colors
  material_color_utilities: ^0.11.1
  
  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true